### ISSUE TITLE
might pill and might seed not showing

### ISSUE THREAD

**Issue by aruchu517** [sir-wilhelm/SmartHunter#14]
might pill and might seed not showing in player status

**Comment by sir-wilhelm** [comment]
They are showing up for me. I'm guessing you might just need to clear your PlayerData.json file.

https://github.com/sir-wilhelm/SmartHunter/releases/tag/1.3.1.1
I have an alpha version you can try, it should auto recreate the files.

**Comment by aruchu517** [comment]
no didn't work.
I have same problem with  r00telement 's one.
r00telement 's one don't even show the demondrug but yours show demondrug.

**Comment by sir-wilhelm** [comment]
I can't reproduce this.
![image](https://user-images.githubusercontent.com/3122458/74582769-ad012700-4f85-11ea-89b9-890868482d4f.png)
![image](https://user-images.githubusercontent.com/3122458/74582772-b4c0cb80-4f85-11ea-8481-9361c5f4f3cd.png)
You'll have to send me a s/s of the overlay/smarthunter to see if I can notice anything.

That's what SmartHunter looks like for me with the fresh zip I downloaded from 1.3.1.1.

r00telement's is super out dated, I'd stick with mine or gabrielefilipp's version.

**Comment by aruchu517** [comment]
Problem solved.
I reinstalled the game and mods.
I don't know how that's a thing, but it work.
