### ISSUE TITLE
monster part, and status gauges not working

### ISSUE THREAD

**Issue by scorpion21b** [sir-wilhelm/SmartHunter#22]
na

**Comment by sir-wilhelm** [comment]
Any more info? 

I'm betting you just need to read the [FAQ](https://github.com/sir-wilhelm/SmartHunter#faq):
>Why don't monster parts and status effects update properly in multiplayer sessions?
>>This data only updates properly for the quest host. This is just the way the game works and it can't be worked around.

**Comment by scorpion21b** [comment]
thank you for enlightening me

**Comment by sir-wilhelm** [comment]
No worries, happy hunting.
