### ISSUE TITLE
Player count is always missing one

### ISSUE THREAD

**Issue by Jichael** [sir-wilhelm/SmartHunter#23]
Hey, been happening since safi update I think, I can't find anything relevant in the logs.

The problem is that there is always one player missing on the overlay (eg. two people hunt, I'll only see myself and not the other one / four people hunt, there will only be three).

Am I the only one that have this issue ? I did not change the default layout, and didn't touch anything between when it was working and now.

Thanks for the mod anyway :)

**Comment by sir-wilhelm** [comment]
I just joined an SoS arena quest and saw 4 people.

**Comment by sir-wilhelm** [comment]
1.5.1.0 appears to be working for me (when I host or join an SoS).

Do you have any more details you can give?

**Comment by Jichael** [comment]
Made some SoS aswell, here is the result :
[ScreenShots.zip](https://github.com/sir-wilhelm/SmartHunter/files/4397232/ScreenShots.zip)

I think it's always the first one to be in the quest, but I'm not sure.

I'm on latest (1.5.1.0) version aswell.

Maybe something went wrong with the autoupdater ? Could you send me your Default.xaml and Config.json so I can diff with mine ?

**Comment by sir-wilhelm** [comment]
That does look like it's missing player 1 for some reason. Could you just try downloading 1.5.1.0 again and running it from a freshly extracted folder? 
https://github.com/sir-wilhelm/SmartHunter/releases

**Comment by Jichael** [comment]
Well, it's working as intended with a new install.
I diff'ed all the .json file as well as the xaml file, found nothing. So it may be the auto update that failed something for some reasons ?
I can't find anything that could help I'm afraid :/

**Comment by sir-wilhelm** [comment]
Strange, I would have expected it to work just fine if it was running 1.5.1.0 and the Default.xaml/Config.json were the same as a fresh install. 

I'm glad the fresh copy is working for ya.
