### ISSUE TITLE
Player and Team Damage Indicator Issues

### ISSUE THREAD

**Issue by junkfoos** [sir-wilhelm/SmartHunter#25]
When I loaded into a hunt with two other friends the team widget only loaded 1 friend and my damage bars but not my other friends damage bar. I did the exact same hunt right after we completed the first and it showed a different set of damage bars (once again only 2). This happened multiple times with different hunts. Later in the day my one friend and I went to my guiding lands and the damage bars didn't even show up for the team widget.

**Comment by sir-wilhelm** [comment]
Sounds similar to #23 could you try downloading a fresh install and let me know how that works?

**Comment by sir-wilhelm** [comment]
let me know if it happen on a new download of the latest version.

https://github.com/sir-wilhelm/SmartHunter/releases
