### ISSUE TITLE
Incorrect Crown Sizes

### ISSUE THREAD

**Issue by jet082** [sir-wilhelm/SmartHunter#26]
The crown size for Scarred Yian Garuga is incorrect. The crown size 1708.48 is indeed gold, but it shows up as silver.

I believe that this is a rounding error and I believe it also impacts many more crown possibilities than this one.

**Comment by jet082** [comment]
The Blackveil mini crown (1885.86) also does not display correctly.

I believe the regular Yian Garuga crowns also have issues.

**Comment by sir-wilhelm** [comment]
This is a rounding issue, and I recall it was reported before: https://github.com/gabrielefilipp/SmartHunter/issues/45

I'll try and take a look at it later this week.

**Comment by sir-wilhelm** [comment]
looking at this a little more I'm not sure where the rounding issue comes into play. I feel like it only impacts crowns on the edge of the threshold.

The monster's ModifiedSizeScale is calculated from it's SizeScale/Scale Modifier (pulled from memory). If I happen to see a monster close to the boundary or if someone knows a specific quest/event that hits the right conditions I'll look into it, but for now I'm going to leave it alone.

**Comment by sir-wilhelm** [comment]
![image](https://user-images.githubusercontent.com/3122458/78413130-a5e8b380-75db-11ea-84d7-0dc1180a89dd.png)
I managed to find one monster at the limit and it looked good to me. 

I'll see if I can find it on a Yian or Blackveil, but I think this is working on the latest version.

**Comment by sir-wilhelm** [comment]
found a silver 1625.14 S. Yian. and it was labeled correctly. 

I'll keep an eye out, but I think this is fixed in the latest version. I have some code clean up/more safi clean up, so I'll cut another version this weekend.

**Comment by jet082** [comment]
Well, a lot of the crowns "on the edge" do work from my experience. However, a handful do not.

If you want to duplicate these conditions, you can use [this mod](https://www.nexusmods.com/monsterhunterworld/mods/1983) (specifically the Guaranteed Big Crowns one) and then enter the Scars Tell the Whole Story Event Quest.

The crown should show up as gold, but it will show up as silver on SmartHunter.

**Comment by sir-wilhelm** [comment]
Thanks for the link, I'll give it a go this afternoon.

**Comment by sir-wilhelm** [comment]
```
Yian Garuga : 1708.482
SS:     0.983999968
SM:     0.8
MSS:    1.2299999
```
Found where I can add a round to fix it.
![image](https://user-images.githubusercontent.com/3122458/78461400-249e2900-768e-11ea-83bc-6e2249b23001.png)
![image](https://user-images.githubusercontent.com/3122458/78461457-b443d780-768e-11ea-95bb-dfa1eb3aa655.png)
This should fix all the edge cases.

I'll make a release later today.

**Comment by jet082** [comment]
It might be worth testing Blackveil as well. You can test that with the same mod (but the mini crown version) and the 5* Here Comes the Deathmaker quest.

Under those conditions it should show up as 1885.86 and should show a mini crown.

That way you can test both the mini and the giant edge cases.
