### ISSUE TITLE
Savage Deviljho Large Crown

### ISSUE THREAD

**Issue by KaitouHAX** [sir-wilhelm/SmartHunter#27]
Honestly i didn't want to create an issue for such a minor thing but there doesn't seem to be any private messaging on github.

Anyway Savage Deviljho's crown was shown as silver by smarthunter but game considered it gold
Size: 2517.86
Image: https://i.imgur.com/jAVIEvf.png

**Comment by sir-wilhelm** [comment]
was this on the latest version? 

Were you on a specific quest?

**Comment by sir-wilhelm** [comment]
https://mhw.poedb.tw/eng/monster/Savage%20Deviljho

looks like 2517.86 should very much be gold, it might have the wrong crown settings. I'll see if I can find an event quest to farm to get a large crown this evening.

**Comment by KaitouHAX** [comment]
it was the crown event quest for the wildspire area
this happened to glavenus's and banbaro's large crowns as well

**Comment by sir-wilhelm** [comment]
![image](https://user-images.githubusercontent.com/3122458/78730127-8914ee80-7901-11ea-96e0-b65d61bdc5d9.png)
mini is working

still looking for a big one.

**Comment by sir-wilhelm** [comment]
![image](https://user-images.githubusercontent.com/3122458/78732760-2889af80-7909-11ea-8725-22855cfad4ba.png)
It should be working on the ~~latest~~next version.

**Comment by sir-wilhelm** [comment]
found the issue, new version incoming.

**Comment by sir-wilhelm** [comment]
https://github.com/sir-wilhelm/SmartHunter/releases/tag/1.5.3.0-alpha
should have the fix, it'll auto-update once I make the final release version.

**Comment by sir-wilhelm** [comment]
Rajang, Savage Deviljho, Deviljho, Glavenus, Acidic Glavenus, Anjanath, Fulgur Anjanath, Pukei-Pukei, Coral Pukei-Pukei, Tobi-Kadachi, Viper Tobi-Kadachi, and Radobaan were all displaying the wrong crowns in some cases.
