### ISSUE TITLE
Incorrect buff displays

### ISSUE THREAD

**Issue by lokiregnarok** [sir-wilhelm/SmartHunter#28]
Ver 1.5.4 (raging brach and furious rajang update) isn't displaying the correct buff status under the player widget. If shows "Immunizer (1) and Hot Drink (12) when outside on quest/expedition and when in seliana, it shows "Hot Drink" followed by some crazy numbers. It also do not display any extra buff you take and seem to cap the number of buff displayed at 4.

**Comment by sir-wilhelm** [comment]
I think you mean 1.5.4.0-alpha. I'm aware, since it's an alpha version I'm still working on finding the updated memory addresses. 

I'll get to them in time, for now I'll release an actual 1.5.4.0 version that has some of the buffs fixed.
