### ISSUE TITLE
Add charge blade weapon timers

### ISSUE THREAD

**Issue by sir-wilhelm** [sir-wilhelm/SmartHunter#31]
Need to fix weapon timers again (see #20 for the last time this came up)

**Comment by sir-wilhelm** [comment]
shield - 180
weapon - 45
phial - 18

**Comment by sir-wilhelm** [comment]
Find address in CE, find weapon address: 
https://github.com/sir-wilhelm/SmartHunter/blob/master/SmartHunter/Game/MhwMemoryUpdater.cs#L138
```
var str = @$"
Equip:  {equipmentAddress:X}
Weapon: {weaponAddress:X}
Buff:   {buffAddress:X}
";
```

https://www.calculator.net/hex-calculator.html
find the difference and divide by 4.

Fixed in: 23a5a7bb4d053be5498d249d7fe7d8ed4ef6ebca.

**Comment by sir-wilhelm** [comment]
Ex: 
Shield Charge address: 649FD798
Weapon address: 649FB420

diff: 2378 (9080) / 4 = 8DE (2270)

**Comment by F-a-y-t-h** [comment]
The pointer path you seem to be using is MonsterHunterWorld.exe+503E2A0>0x8c8>0x1c0>0x76b0>
So they should be
Sharpness (all weapons)
0x20F8 (2 bytes)

Longsword
0x2370 Charge Level (byte)
0x2374 Charge Gauge

Chargeblade
0x2370 Sword Heat
0x2374 Phials (byte)
0x2378 Shield Charge
0x237C Sword Charge

Switchaxe
0x2350 Sword Mode

IG
0x2368 Red Essence
0x236C White Essence
0x2370 Orange Essence

I hope this helps~

**Comment by WX4M** [comment]
Eating adamant seed will lead to Blastscourge's appearing
