### ISSUE TITLE
Master Rank Kulve Taroth

### ISSUE THREAD

**Issue by SyncStelar** [sir-wilhelm/SmartHunter#32]
Smart hunter stops showing Master Rank Kulve Taroth health when she sheds her coat and change zone the first time. (Doesn't show after that too)

**Comment by Lapan** [comment]
It seems pretty random when it happens, but most of the time it's around zone 2. I've only had it last until the last phase once

**Comment by sir-wilhelm** [comment]
I've not been playing much, I hear a workaround is:
>Open map and deselect and re-select her and it should pop back up
