### ISSUE TITLE
"Removable tail" shows incorrect health

### ISSUE THREAD

**Issue by judwaiser** [sir-wilhelm/SmartHunter#35]
As the title says. I play SwAxe and sometimes the "removable tail" gets stuck at one health for a few hits. On a sidenote, would it be possible to add break threshold to monster parts as opposed to the flinch threshold which seems to be the one in place? I noticed I have to deplete the health of some monster parts numerous times for them to truly break.
Should a screenshot be necessary I might get one.

Edit: Seems to be the problem with Odogaron and Coral pukei-pukei so far

**Comment by sir-wilhelm** [comment]
I think it gets stuck there when the monster is stuck in an animation, but it should drop to 0 once the tail falls off.
