### ISSUE TITLE
Linux port of SmartHunter

### ISSUE THREAD

**Issue by Emanem** [sir-wilhelm/SmartHunter#36]
Hi Sir-Wilhelm,

just wanted to let you know I've tried to port this [great app to Linux](https://github.com/Emanem/linux-hunter) - and I credited you in the README.md.
Is not as complete or _nice_ as the one on Windows, but does the job!

Thanks again for the great activity you/community are doing to maintaining this every new MH:W version!

Feel free to ask me any question!

Keep up the great work!

Ps. Integrating Monsters display in the next revision branch!

**Comment by sir-wilhelm** [comment]
That looks cool, best of luck w/ it!
