### ISSUE TITLE
Beginner's question

### ISSUE THREAD

**Issue by Akhaell** [sir-wilhelm/SmartHunter#37]
Hi, I'm sorry to bother you I'm really not used to this website so I don't even know another way to contact you.
I was a Smart Hunter user before r00telement's lack of time, so I managed to get here and see some new version of it. I'm just trying to download that new version of smarthunter so basically I downloaded the big folder on the main page but I can't seem to find it anywhere in the folder.
Don't be mad if that's an idiot question, I'm just trying to figure how to make it work again ^^'

Thanks in advance.

**Comment by jrtaclas** [comment]
get it here https://github.com/sir-wilhelm/SmartHunter/releases

**Comment by Akhaell** [comment]
Is it something to just extract in the big folder ? Or did I simply download the wrong thin and I just need the folder you shared above ? Because in the little folder I can't find any config file

(thanks for the real quick answer ^^)

**Comment by sir-wilhelm** [comment]
You just need to download/extract the SmartHunter.zip file from the releases page.

Here is a direct link:
https://github.com/sir-wilhelm/SmartHunter/releases/download/1.5.8.1/SmartHunter.zip

The config file will be auto generated on first run of the SmartHutner.exe

**Comment by Akhaell** [comment]
Thanks a lot, I totally forgot about the file generating himself ^^'
