### ISSUE TITLE
Failed Patterns [1/8]: CurrentPlayerNamePattern

### ISSUE THREAD

**Issue by adugourd** [sir-wilhelm/SmartHunter#41]
Hi, since the last MHW update, I get this error.

Failed Patterns [1/8]: CurrentPlayerNamePattern

Cheers

**Comment by Celuryl** [comment]
Same here, prevents seeing players stats and damage done

**Comment by sir-wilhelm** [comment]
Duplicate of #40 I'll see if I have time this week to pull in a fix for this, but I've not been playing, so I can't say it's high on my priority list.
